### ISSUE TITLE
 jre8/bin/java: Exec format error (yunohost 11.0.6)

### ISSUE THREAD

**Issue by MX10-AC2N** [YunoHost-Apps/UMS_ynh#33] opened 2022-04-29 14:35 UTC
Hi,
I try install on yunohost 11.0.6 on armbian..
Install finished OK..
but ums.service failed
```
LOGFILE: journalctl
-- Journal begins at Thu 2022-04-28 12:17:03 CEST, ends at Fri 2022-04-29 16:16:36 CEST. --
avril 29 16:01:18 systemd[1]: Started A DLNA UPnP and HTTP(S) Media Server.
avril 29 16:01:19 systemd[1]: ums.service: Main process exited, code=exited, status=126/n/a
avril 29 16:01:19 systemd[1]: ums.service: Failed with result 'exit-code'.
avril 29 16:16:36 systemd[1]: Started A DLNA UPnP and HTTP(S) Media Server.
avril 29 16:16:36 systemd[1]: ums.service: Main process exited, code=exited, status=126/n/a
avril 29 16:16:36 systemd[1]: ums.service: Failed with result 'exit-code'.

LOGFILE: /var/log/ums/ums.log
/opt/yunohost/ums/UMS.sh: 72: exec: jre8/bin/java: Exec format error
/opt/yunohost/ums/UMS.sh: 72: exec: jre8/bin/java: Exec format error
```
here is installation log => https://paste.yunohost.org/itocumalan.sql

Thank a lot.

**Comment by Krakinou** [comment] 2022-04-29 16:27
Hmmm,
Seems that the jdk build is not correct.
What are the output of `java -version` and  `uname -m`?
Also, can you check if there is a jre folder in /opt/yunohost/ums?

**Comment by MX10-AC2N** [comment] 2022-04-30 06:13
Thank @Krakinou 
```
 java -version
Command 'java' not found, did you mean:
  command 'fava' from deb python3-fava
  command 'javr' from deb xc3sprog
  command 'japa' from deb japa
  command 'cava' from deb cava
  command 'jaaa' from deb jaaa
Try: apt install <deb name>
```
Java is not installed by ums installation ?
`uname -m => aarch64`
```
ls -l /opt/yunohost/ums
total 60676
-rw-r----- 1 root ums      166  4 Mar 06:38 BUILD.md
-rw-r----- 1 root ums   195132 14 Mar 08:43 CHANGELOG.txt
drwxr-x--- 4 root ums     4096 29 Apr 16:00 documentation
-rw-r----- 1 root ums     1095 18 Mar  2015 DummyInput.ass
-rw-r----- 1 root ums     3823  1 May  2018 DummyInput.jpg
-rw-r----- 1 root ums     1483  4 Mar 06:38 INSTALL.txt
drwxr-x--- 4 root ums     4096  6 Mar 08:13 jre8
-rw-r----- 1 root ums    17992 25 Nov  2013 LICENSE.txt
drwxr-x--- 2 root ums     4096 29 Apr 16:00 linux
-rw-r----- 1 root ums     3531 11 Mar 09:04 logback.headless.xml
-rw-r----- 1 root ums     3925 11 Mar 09:04 logback.xml
drwxr-x--- 2 root ums     4096 29 Apr 16:00 plugins
-rw-r----- 1 root ums     4125 11 Mar 08:15 README.md
drwxr-x--- 2 root ums    12288 29 Apr 16:00 renderers
-rw-r----- 1 root ums    59685  4 Mar 06:38 UMS.conf
-rw-r----- 1 root ums 61768757 14 Mar 08:50 ums.jar
-rwxr-x--- 1 root ums     1841 11 Mar 09:04 UMS.sh
-rw-r----- 1 root ums      282 15 Jan  2020 VirtualFolders.conf
drwxr-x--- 5 root ums     4096 29 Apr 16:00 web
-rw-r----- 1 root ums     4218  4 Mar 06:38 WEB.conf
```

**Comment by Krakinou** [comment] 2022-04-30 10:18
Ok,
`uname -m => aarch64 `
That's the issue, I did not handle this architecture in the install script:
https://github.com/YunoHost-Apps/UMS_ynh/blob/791ed7fd54608553b90ad564f40eaa8508a6bdd0/scripts/_common.sh#L18

I believe this should be the same as arm64?
Will push a fix by the end of the weekend (don't have a computer right now)

**Comment by Krakinou** [comment] 2022-05-01 19:13
Hi,
I just pushed a fix along with 10.20.0 new version.
Can you try `sudo yunohost app install https://github.com/YunoHost-Apps/ums_ynh/tree/testing` and confirm this is working?

**Comment by MX10-AC2N** [comment] 2022-05-02 10:00
Hi,
Thank a lot, but install failed cause
` WARNING E: Package 'openjdk-8-jre' has no installation candidate`
```
$ apt show openjdk-*-jre
Package: openjdk-11-jre
Version: 11.0.14+9-1~deb11u1
Priority: optional
Section: java
Source: openjdk-11
Maintainer: OpenJDK Team <openjdk-11@packages.debian.org>
Installed-Size: 542 kB
Provides: java-runtime, java10-runtime, java11-runtime, java2-runtime, java5-runtime, java6-runtime, java7-runtime, java8-runtime, java9-runtime
Depends: openjdk-11-jre-headless (= 11.0.14+9-1~deb11u1), libgl1, libharfbuzz0b, libc6 (>= 2.29), libgif7 (>= 5.1), libjpeg62-turbo (>= 1.3.1), libpng16-16 (>= 1.6.2-1), libx11-6, libxext6, libxi6, libxrender1, libxtst6
Recommends: libatk-wrapper-java-jni (>= 0.30.4-0ubuntu2), fonts-dejavu-extra
Breaks: openjdk-11-jre-headless (<< 11.0.11+3-3~)
Replaces: openjdk-11-jre-headless (<< 11.0.11+3-3~)
Homepage: https://openjdk.java.net/
Tag: uitoolkit::gtk
Download-Size: 165 kB
APT-Sources: http://deb.debian.org/debian bullseye/main arm64 Packages
Description: OpenJDK Java runtime, using Hotspot JIT

Package: openjdk-17-jre
Version: 17.0.2+8-1~deb11u1
Priority: optional
Section: java
Source: openjdk-17
Maintainer: OpenJDK Team <openjdk-17@packages.debian.org>
Installed-Size: 509 kB
Provides: java-runtime, java10-runtime, java11-runtime, java12-runtime, java13-runtime, java14-runtime, java15-runtime, java16-runtime, java17-runtime, java2-runtime, java5-runtime, java6-runtime, java7-runtime, java8-runtime, java9-runtime
Depends: openjdk-17-jre-headless (= 17.0.2+8-1~deb11u1), libglib2.0-0 (>= 2.24), libgtk2.0-0 | libgtk-3-0, libxrandr2, libxinerama1, libgl1, libharfbuzz0b, libc6 (>= 2.29), libgif7 (>= 5.1), libjpeg62-turbo (>= 1.3.1), libpng16-16 (>= 1.6.2-1), libx11-6, libxext6, libxi6, libxrender1, libxtst6
Recommends: libatk-wrapper-java-jni (>= 0.30.4-0ubuntu2), fonts-dejavu-extra
Breaks: openjdk-17-jre-headless (<< 17~10)
Replaces: openjdk-17-jre-headless (<< 17~10)
Homepage: https://openjdk.java.net/
Download-Size: 156 kB
APT-Sources: http://deb.debian.org/debian bullseye/main arm64 Packages
Description: OpenJDK Java runtime, using Hotspot JIT

Package: openjdk-6-jre
State: pas un véritable paquet (virtuel)
Package: openjdk-7-jre
State: pas un véritable paquet (virtuel)
Package: openjdk-9-jre
State: pas un véritable paquet (virtuel)
```

Extract of install failed
```
 DEBUG + apt-get --assume-yes --quiet -o=Acquire::Retries=3 -o=Dpkg::Use-Pty=0 --no-remove --option Dpkg::Options::=--force-confdef --option Dpkg::Options::=--force-confold install mediainfo dcraw p7zip openjdk-8-jre --dry-run
241975 WARNING Package openjdk-8-jre is not available, but is referred to by another package.
241976 WARNING This may mean that the package is missing, has been obsoleted, or
241977 WARNING is only available from another source
241979 DEBUG
241980 WARNING E: Package 'openjdk-8-jre' has no installation candidate
241981 DEBUG + ynh_die '--message=Unable to install dependencies'
241982 DEBUG + local legacy_args=mc
241984 DEBUG + args_array=(['m']='message=' ['c']='ret_code=')
241985 DEBUG + local -A args_array
241986 DEBUG + local message
241987 DEBUG + local ret_code
241988 DEBUG + ynh_handle_getopts_args '--message=Unable to install dependencies'
241989 DEBUG + set +o xtrace
242012 DEBUG + ret_code=1
242013 WARNING Unable to install dependencies
```

**Comment by Krakinou** [comment] 2022-05-02 22:27
So,
I never really grasp all these java stuffs...

I think the issue is that you're on bullseye and not on buster and that openjdk-8-jre has been dropped in between, which in turn means that I will have to change dependencies when we will move to bullseye...
 
So, for now, I changed  openjdk dependencies to openjdk-11-jre for aarch64 as this is the only one available for both buster and bullseye : can you try again?
Sorry I can't test more : I don't have any armbian device to work with.

**Comment by Krakinou** [comment] 2022-05-03 06:35
By the way, ums just released a pre-release for 11.0.0 that uses jre17 as internal java according to the [release notes](https://github.com/UniversalMediaServer/UniversalMediaServer/releases/tag/11.0.0-a1)

**Comment by MX10-AC2N** [comment] 2022-05-03 06:38
Hi @Krakinou 
Yes my armbian is under Bullseye kernel 5.15.36 and there is no problem I can test and share..
Do you want try this new pre-release ?

**Comment by MX10-AC2N** [comment] 2022-05-03 07:04
With jre11 the install process finished fine..
Just one warning during install
```
2022-05-03 08:50:26,454: DEBUG - Setting up ca-certificates-java (20190909) ...
2022-05-03 08:50:26,530: DEBUG - /bin/bash: BASH_XTRACEFD: 7: invalid value for trace file descriptor
2022-05-03 08:50:26,546: WARNING - head: impossible d'ouvrir '/etc/ssl/certs/java/cacerts' en lecture: Aucun fichier ou dossier de ce type
```
I can access to UMS web page, so that's work..! Great ..!
Now I will test with my old amp Harman Kardon AVR265 for streaming music over upnp/dlna, cause I try this with Jellyfin but don't really work..
Thank a lot @Krakinou if you want I can test ums 11 install..

**Comment by Krakinou** [comment] 2022-05-03 13:05
Cool!
I will wait for the 11 version to be a full release instead of a prerelease to start working on it : I had some bad experiences in the past :)

**Closed** 2022-05-03 13:29 UTC

**Comment by MX10-AC2N** [comment] 2022-05-07 06:24
Hi @Krakinou and thank again..
I try V10.20 but not working with my old amp Harman Kardon AVR265 so I open issue on UMS github
https://github.com/UniversalMediaServer/UniversalMediaServer/issues/2960
I also see that there is a new release 10.21.0.1 https://github.com/UniversalMediaServer/UniversalMediaServer/releases/tag/10.21.0.1
I fork this repo for create alpha branch and trying to install alpha release but how can change the version of UMS downloaded
Thank

**Comment by Krakinou** [comment] 2022-05-08 10:51
Hello,
I decided to skip 10.21 as there is a bug listed in the release note, so waiting for 10.22 or 11.0.
You have to change the version in the manifest and change the sum in /script/_common.sh to make an update.
What is the output of `uname -m` on your system?

-------- Message d'origine --------
De : MX10-AC2N ***@***.***>
Date : 07/05/2022 06:24 (GMT+00:00)
À : YunoHost-Apps/UMS_ynh ***@***.***>
Cc : Krakinou ***@***.***>, Mention ***@***.***>
Objet : Re: [YunoHost-Apps/UMS_ynh] jre8/bin/java: Exec format error (yunohost 11.0.6) (Issue #33)


Hi @Krakinou<https://github.com/Krakinou> and thank again..
I try V10.20 but not working with my old amp Harman Kardon AVR265 so I open issue on UMS github
UniversalMediaServer/UniversalMediaServer#2960<https://github.com/UniversalMediaServer/UniversalMediaServer/issues/2960>
I also see that there is a new release 10.21.0.1 https://github.com/UniversalMediaServer/UniversalMediaServer/releases/tag/10.21.0.1
I fork this repo for create alpha branch and trying to install alpha release but how can change the version of UMS downloaded
Thank

**Comment by MX10-AC2N** [comment] 2022-05-08 13:29
Hello @Krakinou 
```
    _              _        ___ ____  ____
   / \   _ __ ___ | |  ___ / _ \___ \|___ \__  __
  / _ \ | '_ ` _ \| | / __| (_) |__) | __) \ \/ /
 / ___ \| | | | | | | \__ \\__, / __/ / __/ >  <
/_/   \_\_| |_| |_|_| |___/  /_/_____|_____/_/\_\

Welcome to Armbian 22.05.0-trunk Bullseye with Linux 5.15.36-ac2n

No end-user support: built from trunk

System load:   67%              Up time:       0 min
Memory usage:  14% of 3.70G     IP:            192.168.1.210
CPU temp:      58°C             Usage of /:    6% of 117G
storage/:      81% of 51G

[ General system configuration (beta): armbian-config ]

Last login: Thu May  5 17:30:07 2022 from 192.168.1.230
admin@XXXX:~$ uname -m
aarch64
```
I will try alpha release  thank for your reply...
